.TH basilico "0.211.1" "Dicembre 2024" "BAS.I.LI.CO. Ambiente di sviluppo e Compilatore" "Comandi Utente"
.SH NAME
basilico \- pagina di manuale di BAS.I.LI.CO.
.SH DESCRIPTION
basilico COMPILER
.PP
USO: basilico [opzioni] <file>
.SS "OPZIONI:"
.TP
<file>
File sorgente da caricare
.TP
\fB\-v\fR
Modalità dettagliata (avvisi dettagliati)
.TP
\fB\-c\fR
Compila invece di modificare
.TP
\fB\-x\fR
Compila invece di modificare e invia il risultato alla console
.TP
\fB\-p\fR
Elimina prima tutto il contenuto precompilato
.TP
\fB\-z\fR
Genera codice C senza compilarlo in eseguibile
.TP
\fB\-o\fR <fileinuscita>
Scrivi l'eseguibile in <fileinuscita>
.TP
\fB\-e\fR
Abilita OPTION _EXPLICIT, rendendo obbligatoria la dichiarazione delle variabili (per compilazione; non influisce sul file sorgente o sulle impostazioni globali)
.TP
\fB\-s[\fR:switch=true/false]
Visualizza/modifica le impostazioni del compilatore
.TP
\fB\-l\fR:<line number>
Avvia l'Ambiente di Sviluppo al numero di linea specificato
.PP
.SH "INTERNET"
.B https://github.com/smaxmex/basilico
